name: Android Dev CI

on:
  push:
    branches-ignore: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies
      run: |
        npm install
        npm install @ionic/cli
    - name: Ionic Capacitor Sync
      run: npx ionic capacitor sync --prod
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: android
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Unsigned APK
        path: android/app/build/outputs/apk/debug/app-debug.apk  
        if-no-files-found: error
