name: Android Prod CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies
      run: |
        npm install
        npm install @ionic/cli
    - name: Ionic Capacitor Sync
      run: npx ionic capacitor sync --prod
    - name: Inject secrets
      run: |
        echo "$GOOGLE_SERVICES" > android/app/google-services.json
        echo "$RELEASE_SIGNING_PROPERTIES" >> android/gradle.properties
        echo "$ANDROID_KEYSTORE" | base64 --decode > android/app/clef_android_signature.jks
      shell: bash
      env:
        GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES}}
        ANDROID_KEYSTORE: ${{secrets.ANDROID_KEYSTORE}}
        RELEASE_SIGNING_PROPERTIES: ${{secrets.RELEASE_SIGNING_PROPERTIES}}
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      working-directory: android
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Signed APK
        path: android/app/build/outputs/apk/release/app-release.apk  
        if-no-files-found: error
